/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    blogs: Blog;
    icons: Icon;
    'job-openings': JobOpening;
    'job-applications': JobApplication;
    services: Service;
    'sub-services': SubService;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    icons: IconsSelect<false> | IconsSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'sub-services': SubServicesSelect<false> | SubServicesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'hero-section': HeroSection;
    'services-section': ServicesSection;
    'trusted-by-section': TrustedBySection;
    'case-studies-hero': CaseStudiesHero;
    'case-studies-grid': CaseStudiesGrid;
    'case-studies-page': CaseStudiesPage;
    'testimonials-section': TestimonialsSection;
    'approach-section': ApproachSection;
    'contact-section': ContactSection;
    'footer-section': FooterSection;
    'about-hero': AboutHero;
    'about-us-section': AboutUsSection;
    'about-stats-section': AboutStatsSection;
    'about-mission-section': AboutMissionSection;
    'about-core-values-section': AboutCoreValuesSection;
    'about-team-section': AboutTeamSection;
    'about-cta-section': AboutCtaSection;
    'blogs-page-hero': BlogsPageHero;
    'career-hero': CareerHero;
    'career-stats': CareerStat;
    'career-find-place': CareerFindPlace;
    'career-work-here': CareerWorkHere;
    'career-testimonials': CareerTestimonial;
    'career-spotify': CareerSpotify;
    'career-job-section': CareerJobSection;
    'jobs-section': JobsSection;
    'privacy-policy-section': PrivacyPolicySection;
  };
  globalsSelect: {
    'hero-section': HeroSectionSelect<false> | HeroSectionSelect<true>;
    'services-section': ServicesSectionSelect<false> | ServicesSectionSelect<true>;
    'trusted-by-section': TrustedBySectionSelect<false> | TrustedBySectionSelect<true>;
    'case-studies-hero': CaseStudiesHeroSelect<false> | CaseStudiesHeroSelect<true>;
    'case-studies-grid': CaseStudiesGridSelect<false> | CaseStudiesGridSelect<true>;
    'case-studies-page': CaseStudiesPageSelect<false> | CaseStudiesPageSelect<true>;
    'testimonials-section': TestimonialsSectionSelect<false> | TestimonialsSectionSelect<true>;
    'approach-section': ApproachSectionSelect<false> | ApproachSectionSelect<true>;
    'contact-section': ContactSectionSelect<false> | ContactSectionSelect<true>;
    'footer-section': FooterSectionSelect<false> | FooterSectionSelect<true>;
    'about-hero': AboutHeroSelect<false> | AboutHeroSelect<true>;
    'about-us-section': AboutUsSectionSelect<false> | AboutUsSectionSelect<true>;
    'about-stats-section': AboutStatsSectionSelect<false> | AboutStatsSectionSelect<true>;
    'about-mission-section': AboutMissionSectionSelect<false> | AboutMissionSectionSelect<true>;
    'about-core-values-section': AboutCoreValuesSectionSelect<false> | AboutCoreValuesSectionSelect<true>;
    'about-team-section': AboutTeamSectionSelect<false> | AboutTeamSectionSelect<true>;
    'about-cta-section': AboutCtaSectionSelect<false> | AboutCtaSectionSelect<true>;
    'blogs-page-hero': BlogsPageHeroSelect<false> | BlogsPageHeroSelect<true>;
    'career-hero': CareerHeroSelect<false> | CareerHeroSelect<true>;
    'career-stats': CareerStatsSelect<false> | CareerStatsSelect<true>;
    'career-find-place': CareerFindPlaceSelect<false> | CareerFindPlaceSelect<true>;
    'career-work-here': CareerWorkHereSelect<false> | CareerWorkHereSelect<true>;
    'career-testimonials': CareerTestimonialsSelect<false> | CareerTestimonialsSelect<true>;
    'career-spotify': CareerSpotifySelect<false> | CareerSpotifySelect<true>;
    'career-job-section': CareerJobSectionSelect<false> | CareerJobSectionSelect<true>;
    'jobs-section': JobsSectionSelect<false> | JobsSectionSelect<true>;
    'privacy-policy-section': PrivacyPolicySectionSelect<false> | PrivacyPolicySectionSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Create and manage all case studies used across the site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left empty. Used for URL (e.g., strengthening-identity-security-compliance)
   */
  slug?: string | null;
  image?: (number | null) | Media;
  category: string;
  iconType?: ('realEstate' | 'finance' | 'healthcare') | null;
  icon?: (number | null) | Icon;
  description: string;
  /**
   * Old link field for backward compatibility
   */
  link?: string | null;
  heroBackgroundImage?: (number | null) | Media;
  heroLogo?: (number | null) | Media;
  /**
   * Description shown in hero section below title
   */
  introDescription?: string | null;
  solutionTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  clientOverview?: {
    clientName?: string | null;
    industry?: string | null;
    location?: string | null;
    size?: string | null;
  };
  challenges?: {
    title?: string | null;
    description?: string | null;
    challengeItems?:
      | {
          challenge: string;
          id?: string | null;
        }[]
      | null;
  };
  howNCGHelped?: {
    title?: string | null;
    subtitle?: string | null;
    solutions?:
      | {
          image?: (number | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  solutionsImplemented?: {
    title?: string | null;
    description?: string | null;
    solutionItems?:
      | {
          solution: string;
          id?: string | null;
        }[]
      | null;
    iconImage?: (number | null) | Media;
  };
  valueDelivered?: {
    title?: string | null;
    valueCards?:
      | {
          /**
           * Display number (e.g., "01", "02", "03")
           */
          number?: string | null;
          image?: (number | null) | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload SVG icons and reuse them across case studies
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons".
 */
export interface Icon {
  id: number;
  name: string;
  svg: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage blog posts displayed on the Blogs page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left empty. Used for URL (e.g., why-cybersecurity-awareness-is-everyones-responsibility)
   */
  slug?: string | null;
  date: string;
  description: string;
  image?: (number | null) | Media;
  /**
   * Old link field for backward compatibility
   */
  link?: string | null;
  heroBackgroundImage?: (number | null) | Media;
  /**
   * Estimated reading time (e.g., "15 Min Read")
   */
  readTime?: string | null;
  contentSections?:
    | {
        sectionType: 'titleParagraph' | 'bulletList' | 'quote' | 'numberedList' | 'image';
        sectionTitle?: string | null;
        paragraphs?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        introParagraph?: string | null;
        bulletItems?:
          | {
              highlightText?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        quoteText?: string | null;
        numberedItems?:
          | {
              highlightText?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        sectionImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  enableSocialSharing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage job opening listings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  title: string;
  /**
   * Auto-generated from title if left empty. Used for URL (e.g., cybersecurity-analyst)
   */
  slug?: string | null;
  location: string;
  type: 'full-time' | 'part-time' | 'full-time-hybrid' | 'hybrid' | 'remote';
  applyByDate: string;
  description: string;
  heroImage?: (number | null) | Media;
  image: number | Media;
  /**
   * Full job description shown on detail page
   */
  roleDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  companyIntroduction?: string | null;
  responsibilities?:
    | {
        responsibility: string;
        id?: string | null;
      }[]
    | null;
  requiredSkills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  attributes?:
    | {
        attribute: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  howToApply?: string | null;
  department?: string | null;
  remoteStatus?: ('hybrid' | 'remote' | 'on-site') | null;
  /**
   * Optional link to the job detail page (e.g., /jobs/cybersecurity-analyst)
   */
  link?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * View submitted job applications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  jobOpening: number | JobOpening;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  location: string;
  languageSkills: ('swedish' | 'english' | 'finnish' | 'danish' | 'other')[];
  securityCheckConsent: 'yes' | 'no';
  yearsOfExperience: string;
  swedishTechIndustry: 'yes' | 'no';
  strategicPlansExperience: 'yes' | 'no';
  resume: number | Media;
  additionalFiles?: (number | Media)[] | null;
  coverLetter?: string | null;
  privacyPolicyConsent: boolean;
  futureOpportunitiesConsent?: boolean | null;
  linkedinUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage all main services used across the site. ⚠️ Note: New services are automatically added to the homepage Services Section. To display them, go to Globals > Services Section and select which sub-services to show for each service.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * URL-friendly identifier (auto-generated from title if not provided)
   */
  slug?: string | null;
  title: string;
  description: string;
  heroImage?: (number | null) | Media;
  heroAlt?: string | null;
  /**
   * Tagline above hero title (e.g., "YOUR TRUSTED IDENTITY SECURITY PARTNER")
   */
  heroTagline?: string | null;
  /**
   * Main heading for hero section
   */
  heroTitle?: string | null;
  /**
   * Subtitle/description for hero section
   */
  heroSubtitle?: string | null;
  /**
   * Title for sub-services section
   */
  subServiceTitle?: string | null;
  /**
   * Description for sub-services section
   */
  subServiceDescription?: string | null;
  /**
   * Title for CTA section
   */
  ctaTitle?: string | null;
  /**
   * Description for CTA section
   */
  ctaDescription?: string | null;
  /**
   * Title for advantages section (e.g., "Identity Security Isn't Just An IT Concern – It's A Business Imperative")
   */
  advantagesTitle?: string | null;
  /**
   * Description/intro text for advantages section
   */
  advantagesDescription?: string | null;
  /**
   * Add advantage cards (maximum 4 cards allowed, e.g., Identity Visibility, Reduce Attack Surface, Regulatory Alignment, Executive Trust)
   */
  advantages?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Label text for case studies section (e.g., "case studies")
   */
  caseStudiesLabel?: string | null;
  /**
   * Hero title for case studies section. Use **text** to highlight text in blue (e.g., "Identity Security In **Action**")
   */
  caseStudiesHeroTitle?: string | null;
  /**
   * Background image for the case studies parallax hero section
   */
  caseStudiesHeroImage?: (number | null) | Media;
  /**
   * Introductory text for case studies section
   */
  caseStudiesIntro?: string | null;
  caseStudies?: (number | CaseStudy)[] | null;
  /**
   * Sub-services related to this service
   */
  subServices?: (number | SubService)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create and manage sub-services (detailed service offerings)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-services".
 */
export interface SubService {
  id: number;
  /**
   * URL-friendly identifier (auto-generated from title if not provided)
   */
  slug: string;
  /**
   * Services this sub-service belongs to (can belong to multiple services)
   */
  services: (number | Service)[];
  title: string;
  description: string;
  /**
   * Order for displaying sub-services within a service
   */
  order?: number | null;
  heroImage?: (number | null) | Media;
  /**
   * Main heading for hero section
   */
  heroTitle?: string | null;
  /**
   * Subtitle/description for hero section
   */
  heroSubtitle?: string | null;
  /**
   * Title for importance section (e.g., "The Importance of IGA in Modern Cybersecurity")
   */
  importanceTitle?: string | null;
  /**
   * Description for importance section
   */
  importanceDescription?: string | null;
  /**
   * Image for importance section
   */
  importanceImage?: (number | null) | Media;
  /**
   * Title for download banner (e.g., "Mastering Identity Governance: Key Strategies For 2025")
   */
  downloadBannerTitle?: string | null;
  /**
   * Description for download banner
   */
  downloadBannerDescription?: string | null;
  /**
   * Button text (e.g., "Download Now")
   */
  downloadBannerButtonText?: string | null;
  /**
   * Button link URL
   */
  downloadBannerButtonLink?: string | null;
  /**
   * Document/guide image for download banner
   */
  downloadBannerImage?: (number | null) | Media;
  /**
   * Title for challenges section (e.g., "Key Challenges We Can Help You Overcome")
   */
  challengesTitle?: string | null;
  /**
   * Description for challenges section
   */
  challengesDescription?: string | null;
  /**
   * Button text (e.g., "Start Assessment")
   */
  challengesButtonText?: string | null;
  /**
   * Button link URL
   */
  challengesButtonLink?: string | null;
  /**
   * Add challenge cards (maximum 4 cards)
   */
  challenges?:
    | {
        /**
         * Challenge number (e.g., "01", "02")
         */
        number?: string | null;
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for benefits section (e.g., "Benefits Of Implementing IGA")
   */
  benefitsTitle?: string | null;
  /**
   * Description/intro for benefits section
   */
  benefitsDescription?: string | null;
  /**
   * Conclusion text after benefits cards
   */
  benefitsConclusion?: string | null;
  /**
   * Button text (e.g., "Book Now")
   */
  benefitsButtonText?: string | null;
  /**
   * Button link URL
   */
  benefitsButtonLink?: string | null;
  /**
   * Add benefit cards
   */
  advantages?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for core features section (e.g., "Core Features We Focus On In IGA Products")
   */
  coreFeaturesTitle?: string | null;
  /**
   * Description/intro for core features section
   */
  coreFeaturesDescription?: string | null;
  /**
   * Image for core features section
   */
  coreFeaturesImage?: (number | null) | Media;
  /**
   * List of core features
   */
  coreFeatures?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for IGA services section (e.g., "Our IGA Services")
   */
  igaServicesTitle?: string | null;
  /**
   * Description for IGA services section
   */
  igaServicesDescription?: string | null;
  /**
   * Add IGA service cards (add as many as needed)
   */
  igaServices?:
    | {
        /**
         * Service number (e.g., "01", "02")
         */
        number?: string | null;
        title: string;
        description: string;
        /**
         * Background pattern/image for the card
         */
        backgroundImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Title for success stories section (e.g., "Proven Outcomes And Success Stories")
   */
  successStoriesTitle?: string | null;
  /**
   * Description for success stories section
   */
  successStoriesDescription?: string | null;
  /**
   * CTA text (e.g., "Explore our resources section for more detailed case studies and insights.")
   */
  successStoriesCtaText?: string | null;
  /**
   * CTA link URL
   */
  successStoriesCtaLink?: string | null;
  /**
   * Background image for success stories section
   */
  successStoriesBackgroundImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'icons';
        value: number | Icon;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'sub-services';
        value: number | SubService;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  image?: T;
  category?: T;
  iconType?: T;
  icon?: T;
  description?: T;
  link?: T;
  heroBackgroundImage?: T;
  heroLogo?: T;
  introDescription?: T;
  solutionTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  clientOverview?:
    | T
    | {
        clientName?: T;
        industry?: T;
        location?: T;
        size?: T;
      };
  challenges?:
    | T
    | {
        title?: T;
        description?: T;
        challengeItems?:
          | T
          | {
              challenge?: T;
              id?: T;
            };
      };
  howNCGHelped?:
    | T
    | {
        title?: T;
        subtitle?: T;
        solutions?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  solutionsImplemented?:
    | T
    | {
        title?: T;
        description?: T;
        solutionItems?:
          | T
          | {
              solution?: T;
              id?: T;
            };
        iconImage?: T;
      };
  valueDelivered?:
    | T
    | {
        title?: T;
        valueCards?:
          | T
          | {
              number?: T;
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  description?: T;
  image?: T;
  link?: T;
  heroBackgroundImage?: T;
  readTime?: T;
  contentSections?:
    | T
    | {
        sectionType?: T;
        sectionTitle?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        introParagraph?: T;
        bulletItems?:
          | T
          | {
              highlightText?: T;
              description?: T;
              id?: T;
            };
        quoteText?: T;
        numberedItems?:
          | T
          | {
              highlightText?: T;
              description?: T;
              id?: T;
            };
        sectionImage?: T;
        id?: T;
      };
  enableSocialSharing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icons_select".
 */
export interface IconsSelect<T extends boolean = true> {
  name?: T;
  svg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  type?: T;
  applyByDate?: T;
  description?: T;
  heroImage?: T;
  image?: T;
  roleDescription?: T;
  companyIntroduction?: T;
  responsibilities?:
    | T
    | {
        responsibility?: T;
        id?: T;
      };
  requiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  attributes?:
    | T
    | {
        attribute?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  howToApply?: T;
  department?: T;
  remoteStatus?: T;
  link?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  jobOpening?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  location?: T;
  languageSkills?: T;
  securityCheckConsent?: T;
  yearsOfExperience?: T;
  swedishTechIndustry?: T;
  strategicPlansExperience?: T;
  resume?: T;
  additionalFiles?: T;
  coverLetter?: T;
  privacyPolicyConsent?: T;
  futureOpportunitiesConsent?: T;
  linkedinUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  heroImage?: T;
  heroAlt?: T;
  heroTagline?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  subServiceTitle?: T;
  subServiceDescription?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  advantagesTitle?: T;
  advantagesDescription?: T;
  advantages?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  caseStudiesLabel?: T;
  caseStudiesHeroTitle?: T;
  caseStudiesHeroImage?: T;
  caseStudiesIntro?: T;
  caseStudies?: T;
  subServices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-services_select".
 */
export interface SubServicesSelect<T extends boolean = true> {
  slug?: T;
  services?: T;
  title?: T;
  description?: T;
  order?: T;
  heroImage?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  importanceTitle?: T;
  importanceDescription?: T;
  importanceImage?: T;
  downloadBannerTitle?: T;
  downloadBannerDescription?: T;
  downloadBannerButtonText?: T;
  downloadBannerButtonLink?: T;
  downloadBannerImage?: T;
  challengesTitle?: T;
  challengesDescription?: T;
  challengesButtonText?: T;
  challengesButtonLink?: T;
  challenges?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  benefitsTitle?: T;
  benefitsDescription?: T;
  benefitsConclusion?: T;
  benefitsButtonText?: T;
  benefitsButtonLink?: T;
  advantages?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  coreFeaturesTitle?: T;
  coreFeaturesDescription?: T;
  coreFeaturesImage?: T;
  coreFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  igaServicesTitle?: T;
  igaServicesDescription?: T;
  igaServices?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
        id?: T;
      };
  successStoriesTitle?: T;
  successStoriesDescription?: T;
  successStoriesCtaText?: T;
  successStoriesCtaLink?: T;
  successStoriesBackgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage homepage hero section content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  id: number;
  /**
   * Use \n for line breaks
   */
  mainHeading: string;
  /**
   * Fallback background image. Use "Animated Background Images" below for dynamic backgrounds.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * Texts that will be typed and deleted in sequence. Each text corresponds to a background image.
   */
  animatedTexts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Background images that change with each animated text. Order should match the animated texts above. Used for desktop screens (lg and above).
   */
  backgroundImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Background images for mobile and tablet screens. Order should match the animated texts above. If not provided, desktop images will be used.
   */
  mobileTabletBackgroundImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  callToAction: {
    description: string;
    /**
     * Use \n for line breaks
     */
    ctaHeading: string;
    ctaLink: string;
    /**
     * Hex color code
     */
    backgroundColor: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage homepage services section - select existing services and their sub-services
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section".
 */
export interface ServicesSection {
  id: number;
  /**
   * Services section title (use \n for line breaks)
   */
  sectionTitle: string;
  /**
   * Select services to display on the homepage. ⚠️ NOTE: New services are automatically added here when created. For existing services, click "+ Add New" to add them. For each service, select which sub-services to show below.
   */
  services?:
    | {
        /**
         * Select an existing service from the Services collection. Note: New services are automatically added here when created, but you still need to select their sub-services below.
         */
        service: number | Service;
        /**
         * Select sub-services to display for this service. Sub-services can belong to multiple services.
         */
        subServices?: (number | SubService)[] | null;
        /**
         * Service image to display in the featured card. This image is specific to this service entry and is separate from sub-service images.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage trusted by / clients section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted-by-section".
 */
export interface TrustedBySection {
  id: number;
  overline: string;
  heading: string;
  description: string;
  clients?:
    | {
        name: string;
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage case studies hero section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-hero".
 */
export interface CaseStudiesHero {
  id: number;
  overline: string;
  /**
   * Use \n for line breaks
   */
  heading: string;
  backgroundImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage case studies cards
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-grid".
 */
export interface CaseStudiesGrid {
  id: number;
  /**
   * Select up to 3 case studies to feature on the homepage
   */
  selectedCaseStudies?: (number | CaseStudy)[] | null;
  buttonText: string;
  buttonLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage hero and grid for the Case Studies page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-page".
 */
export interface CaseStudiesPage {
  id: number;
  hero: {
    overline: string;
    heading: string;
    backgroundImage?: (number | null) | Media;
    introText: string;
  };
  grid?: {
    selectedCaseStudies?: (number | CaseStudy)[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage client testimonials
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-section".
 */
export interface TestimonialsSection {
  id: number;
  overline: string;
  testimonials?:
    | {
        name: string;
        position: string;
        company: string;
        image?: (number | null) | Media;
        quote: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage our approach section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach-section".
 */
export interface ApproachSection {
  id: number;
  title: string;
  heading: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  steps?:
    | {
        /**
         * Step number (e.g., "01", "02")
         */
        id: string;
        title: string;
        description: string;
        image?: (number | null) | Media;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage contact section and team member
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section".
 */
export interface ContactSection {
  id: number;
  heading: string;
  teamMember: {
    name: string;
    position: string;
    image?: (number | null) | Media;
    certifications?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    linkedinUrl?: string | null;
  };
  submitButtonText: string;
  privacyText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage footer contact and office information
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-section".
 */
export interface FooterSection {
  id: number;
  contactUs: {
    phoneHeading: string;
    phone: {
      sweden: string;
      denmark: string;
    };
    emailHeading: string;
    email: string;
  };
  followUs: {
    title: string;
  };
  bottomBar: {
    copyrightText: string;
    privacyLabel: string;
    privacyHref: string;
  };
  sweden: {
    title: string;
    officeHeading: string;
    addressLine1: string;
    addressLine2: string;
  };
  malmo: {
    title: string;
    officeHeading: string;
    addressLine1: string;
    addressLine2: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage About page hero content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero".
 */
export interface AboutHero {
  id: number;
  quote: string;
  /**
   * Enter words or phrases to highlight in blue (text-blue-400). Separate multiple items with commas. Example: excellence, innovation, trust
   */
  highlightWords?: string | null;
  attribution: string;
  backgroundVideo?: (number | null) | Media;
  overlayOpacity: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage About Us content and image
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-section".
 */
export interface AboutUsSection {
  id: number;
  sectionLabel: string;
  heading: string;
  image?: (number | null) | Media;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage About page statistics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-stats-section".
 */
export interface AboutStatsSection {
  id: number;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage mission title and description
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-mission-section".
 */
export interface AboutMissionSection {
  id: number;
  title: string;
  description: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage core values cards
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-core-values-section".
 */
export interface AboutCoreValuesSection {
  id: number;
  title: string;
  subtitle: string;
  values?:
    | {
        icon?: (number | null) | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage team section and members
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-team-section".
 */
export interface AboutTeamSection {
  id: number;
  title: string;
  description?: string | null;
  members?:
    | {
        image?: (number | null) | Media;
        name: string;
        role: string;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage CTA content and background
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-cta-section".
 */
export interface AboutCtaSection {
  id: number;
  title: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  backgroundImage?: (number | null) | Media;
  overlayOpacity: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero content for the Blogs page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs-page-hero".
 */
export interface BlogsPageHero {
  id: number;
  heading: string;
  backgroundImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Career page hero section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-hero".
 */
export interface CareerHero {
  id: number;
  backgroundImage: number | Media;
  title: string;
  subtitle: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Career page statistics section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-stats".
 */
export interface CareerStat {
  id: number;
  title: string;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Career page "Find Your Place at NCG" section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-find-place".
 */
export interface CareerFindPlace {
  id: number;
  image: number | Media;
  tagline: string;
  title: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Career page "What It's Like to Work Here" section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-work-here".
 */
export interface CareerWorkHere {
  id: number;
  title: string;
  cards?:
    | {
        number: string;
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Career page testimonials section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-testimonials".
 */
export interface CareerTestimonial {
  id: number;
  testimonials?:
    | {
        image: number | Media;
        name: string;
        role: string;
        quote: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Career page Spotify section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-spotify".
 */
export interface CareerSpotify {
  id: number;
  /**
   * Upload a custom icon (SVG/PNG). If not uploaded, the default Spotify icon will be used.
   */
  icon?: (number | null) | Media;
  title: string;
  description: string;
  buttonText: string;
  spotifyLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage job openings section - heading, CTA, and select 3 featured jobs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-job-section".
 */
export interface CareerJobSection {
  id: number;
  heading: string;
  buttonText: string;
  buttonLink: string;
  /**
   * Select exactly 3 jobs to display in this section
   */
  selectedJobs?: (number | JobOpening)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Jobs page - background image, heading, description, and select jobs to display
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs-section".
 */
export interface JobsSection {
  id: number;
  backgroundImage: number | Media;
  heading: string;
  description: string;
  /**
   * Select which jobs to display on the Jobs page
   */
  selectedJobs?: (number | JobOpening)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage Privacy Policy page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-section".
 */
export interface PrivacyPolicySection {
  id: number;
  hero: {
    backgroundImage: number | Media;
    title: string;
    effectiveDate: string;
  };
  introduction: string;
  privacyPolicySections?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  cookiesPolicy: {
    introduction: string;
    sections?:
      | {
          title: string;
          content: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  mainHeading?: T;
  backgroundImage?: T;
  animatedTexts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  backgroundImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  mobileTabletBackgroundImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  callToAction?:
    | T
    | {
        description?: T;
        ctaHeading?: T;
        ctaLink?: T;
        backgroundColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-section_select".
 */
export interface ServicesSectionSelect<T extends boolean = true> {
  sectionTitle?: T;
  services?:
    | T
    | {
        service?: T;
        subServices?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusted-by-section_select".
 */
export interface TrustedBySectionSelect<T extends boolean = true> {
  overline?: T;
  heading?: T;
  description?: T;
  clients?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-hero_select".
 */
export interface CaseStudiesHeroSelect<T extends boolean = true> {
  overline?: T;
  heading?: T;
  backgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-grid_select".
 */
export interface CaseStudiesGridSelect<T extends boolean = true> {
  selectedCaseStudies?: T;
  buttonText?: T;
  buttonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-page_select".
 */
export interface CaseStudiesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        overline?: T;
        heading?: T;
        backgroundImage?: T;
        introText?: T;
      };
  grid?:
    | T
    | {
        selectedCaseStudies?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-section_select".
 */
export interface TestimonialsSectionSelect<T extends boolean = true> {
  overline?: T;
  testimonials?:
    | T
    | {
        name?: T;
        position?: T;
        company?: T;
        image?: T;
        quote?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approach-section_select".
 */
export interface ApproachSectionSelect<T extends boolean = true> {
  title?: T;
  heading?: T;
  description?: T;
  buttonText?: T;
  buttonLink?: T;
  steps?:
    | T
    | {
        id?: T;
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-section_select".
 */
export interface ContactSectionSelect<T extends boolean = true> {
  heading?: T;
  teamMember?:
    | T
    | {
        name?: T;
        position?: T;
        image?: T;
        certifications?:
          | T
          | {
              name?: T;
              id?: T;
            };
        linkedinUrl?: T;
      };
  submitButtonText?: T;
  privacyText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-section_select".
 */
export interface FooterSectionSelect<T extends boolean = true> {
  contactUs?:
    | T
    | {
        phoneHeading?: T;
        phone?:
          | T
          | {
              sweden?: T;
              denmark?: T;
            };
        emailHeading?: T;
        email?: T;
      };
  followUs?:
    | T
    | {
        title?: T;
      };
  bottomBar?:
    | T
    | {
        copyrightText?: T;
        privacyLabel?: T;
        privacyHref?: T;
      };
  sweden?:
    | T
    | {
        title?: T;
        officeHeading?: T;
        addressLine1?: T;
        addressLine2?: T;
      };
  malmo?:
    | T
    | {
        title?: T;
        officeHeading?: T;
        addressLine1?: T;
        addressLine2?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-hero_select".
 */
export interface AboutHeroSelect<T extends boolean = true> {
  quote?: T;
  highlightWords?: T;
  attribution?: T;
  backgroundVideo?: T;
  overlayOpacity?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-section_select".
 */
export interface AboutUsSectionSelect<T extends boolean = true> {
  sectionLabel?: T;
  heading?: T;
  image?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-stats-section_select".
 */
export interface AboutStatsSectionSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-mission-section_select".
 */
export interface AboutMissionSectionSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-core-values-section_select".
 */
export interface AboutCoreValuesSectionSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-team-section_select".
 */
export interface AboutTeamSectionSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  members?:
    | T
    | {
        image?: T;
        name?: T;
        role?: T;
        bio?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-cta-section_select".
 */
export interface AboutCtaSectionSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  buttonText?: T;
  buttonLink?: T;
  backgroundImage?: T;
  overlayOpacity?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs-page-hero_select".
 */
export interface BlogsPageHeroSelect<T extends boolean = true> {
  heading?: T;
  backgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-hero_select".
 */
export interface CareerHeroSelect<T extends boolean = true> {
  backgroundImage?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  buttonText?: T;
  buttonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-stats_select".
 */
export interface CareerStatsSelect<T extends boolean = true> {
  title?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-find-place_select".
 */
export interface CareerFindPlaceSelect<T extends boolean = true> {
  image?: T;
  tagline?: T;
  title?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-work-here_select".
 */
export interface CareerWorkHereSelect<T extends boolean = true> {
  title?: T;
  cards?:
    | T
    | {
        number?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-testimonials_select".
 */
export interface CareerTestimonialsSelect<T extends boolean = true> {
  testimonials?:
    | T
    | {
        image?: T;
        name?: T;
        role?: T;
        quote?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-spotify_select".
 */
export interface CareerSpotifySelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  buttonText?: T;
  spotifyLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-job-section_select".
 */
export interface CareerJobSectionSelect<T extends boolean = true> {
  heading?: T;
  buttonText?: T;
  buttonLink?: T;
  selectedJobs?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs-section_select".
 */
export interface JobsSectionSelect<T extends boolean = true> {
  backgroundImage?: T;
  heading?: T;
  description?: T;
  selectedJobs?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy-section_select".
 */
export interface PrivacyPolicySectionSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        title?: T;
        effectiveDate?: T;
      };
  introduction?: T;
  privacyPolicySections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  cookiesPolicy?:
    | T
    | {
        introduction?: T;
        sections?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}